services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: indigov
    volumes:
      - psql:/var/lib/postgresql/data
    ports:
      - 5432:5432
volumes:
  psql:
